import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import Providers from './providers'
import { Box, HStack } from '@chakra-ui/react'
import { Sidebar } from '@/components/Sidebar'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ja">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          <Box bg="gray.800" w="100vw" h="100vh" color="white">
            <HStack align="start" spacing={0} h="full">
              <Sidebar />
              <Box w="full" p={3}>
                {children}
              </Box>
            </HStack>
          </Box>
        </Providers>
      </body>
    </html>
  )
}
